project:
  type: website
  output-dir: docs


website:
  title: "Sara Antentas Oliveras"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true