project:
  type: website
  resources:
    - files/**


website:
  title: "Sara Antentas Oliveras"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



